name: Deploy GCP VM

on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: 'Terraform Action (plan or apply)'
        required: true
        default: 'plan'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan or Apply
        run: |
          terraform ${{ github.event.inputs.tf_action }} \
            -var "project_id=YOUR_PROJECT_ID"
