name: Deploy GCP VM with Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action (plan or apply)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan or Apply
        run: |
          if [ "${{ github.event.inputs.action }}" = "plan" ]; then
            terraform plan -var="project_id=YOUR_PROJECT_ID"
          elif [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve -var="project_id=YOUR_PROJECT_ID"
          else
            echo "Invalid action input"
            exit 1
          fi