name: Terraform GCP VM

on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform Action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      project_id:
        description: "GCP Project ID"
        required: true
        default: "your-project-id"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.tf_action == 'plan'
        run: terraform plan -var="project_id=${{ github.event.inputs.project_id }}"

      - name: Terraform Apply
        if: github.event.inputs.tf_action == 'apply'
        run: terraform apply -auto-approve -var="project_id=${{ github.event.inputs.project_id }}"

      - name: Terraform Destroy
        if: github.event.inputs.tf_action == 'destroy'
        run: terraform destroy -auto-approve -var="project_id=${{ github.event.inputs.project_id }}"
