name: Deploy GCP VM with Terraform

on:
  workflow_dispatch: # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="project_id=YOUR_PROJECT_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="project_id=YOUR_PROJECT_ID"
